apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: py-main-app
  labels:
    app: py-main-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  py-main-app
    spec:
      containers:
      - image:  dmlgl/py-main-app:2
        name:  py-main-app
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name:  PORT
          value:  '80'
        - name: RABBITMQ_CONNECTION
          valueFrom:
            secretKeyRef:
              key: url
              name: rabbitmq-connection
        ports:
        - containerPort: 8080
          name:  metrics
---
kind: Service
apiVersion: v1
metadata:
  name: py-main-app
spec:
  selector:
    app: py-main-app
  ports:
  - name: metrics
    port: 8080
  type: NodePort